### PR TITLE
Trying to embed Eventbrite in HTTPS iframe

### PR DESCRIPTION
**Pull request by timtomch**

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Feb 04, 2015 at 10:50:48AM -0800, Thomas Guignard wrote:

> - Trying to embed Eventbrite in HTTPS iframe

It looks like this worked :).  Since Eventbrite does support HTTPS,
it's probably worth updating workshop-template to use HTTPS as well
[1](https://github.com/swcarpentry/workshop-template/blob/14eeb801f02404bd2aee603607cb4e419d003825/index.html#L37).  Do you want to create the upstream pull request, or shall I?

**Comment by timtomch** [comment]
I thought of it and then wondered if there was a valid reason not to specify the protocol in the iframe src. I'm far from being a web expert and it appears there can be issues when embedding HTTPS iframes in HTTP documents, since an attacker can still replace the iframe src value [1](https://security.stackexchange.com/questions/894/are-there-security-issues-with-embedding-an-https-iframe-on-an-http-page).

Said otherwise: would this pose a problem for workshop pages served over HTTP?

**Comment by wking** [comment]
On Wed, Feb 04, 2015 at 11:02:30AM -0800, Thomas Guignard wrote:

> I thought of it and then wondered if there was a valid reason not to
> specify the protocol in the iframe src. I'm far from being a web
> expert and it appears there can be issues when embedding HTTPS
> iframes in HTTP documents, since an attacker can still replace the
> iframe src value [1].

The caveats there are warning about trusting the validity of HTTPS
content linked from an HTTP page.  That's a valid concern, but
certainly no worse than the doubtful validity of HTTP content linked
from an HTTP page.  In our case, we're just retreiving Eventbrite
content, not submitting passwords or other sensitive content, so I'm
comfortable going with HTTPS here.

**Comment by timtomch** [comment]
Makes sense. I have limited access to my computer right now, so if you can be bothered, go ahead and PR that change. Thanks!

**Comment by wking** [comment]
On Wed, Feb 04, 2015 at 11:33:15AM -0800, Thomas Guignard wrote:

> I have limited access to my computer right now, so if you can be
> bothered, go ahead and PL that change. Thanks!

Done with swcarpentry/workshop-template#153.

It looks like folks actually register (possibly with credit card info)
through this iframe, so my position is that we _must_ use HTTPS for
both the iframe and the workshop repository as a whole.  If you're not
having your students pay to register it's less critical, but still a
good idea, to use HTTPS.

**Comment by gvwilson** [comment]
@pipitone @r-gaia-cs did one of you figure out this iframe stuff for us 
in the first place?

**Pull request merged**
